name: Second Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: first-workflow-output
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{secrets.GITHUB_TOKEN}}

      - name: Use output
        run: cat output.txt