name: Testing
on:
  workflow_dispatch:
    inputs:
      book:
        options:
          - 'yes'
          - 'no'
        default: 'no'
        description: Read or not
        required: true
      price:
        options:
          - '100'
          - '200'
        required: true
        default: '200'
        description: Price of the book

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check
      run: |
        echo ${{github.event.inputs.book}}
        echo ${{github.event.inputs.price}}
