name: Print Service Names
on:
  workflow_dispatch:

jobs:
  print-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["apple", "mango", "banana"]
    steps:
      - name: Print service name
        run: |
          echo "Service Name: ${{ matrix.service }}"
