name: Print Service Names
on:
  workflow_dispatch:
    inputs:
      SERVICE_NAMES:
        description: 'Comma-separated list of service names'
        required: false
        default: apple mango banana

jobs:
  print-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ inputs.SERVICE_NAMES }}
    steps:
      - name: Print service name
        run: |
          echo "Service Name: ${{ matrix.service }}"
