name: Read and Print Commit ID

on:
  push:
    branches:
      - master
      - main

jobs:
  save-commit-id:
    runs-on: ubuntu-latest
    outputs:
      commit-id: ${{ steps.get-commit-id.outputs.commit-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit ID
        id: get-commit-id
        run: echo "::set-output name=commit-id::$(git rev-parse HEAD)"

  print-commit-id:
    runs-on: ubuntu-latest
    needs: save-commit-id
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print commit ID
        run: echo "Commit ID from previous job: ${{ needs.save-commit-id.outputs.commit-id }}"
