name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create output file
        run: echo "This is some output data from the first workflow" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: first-workflow-output
          path: output.txt
