name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C07BDESKPBQ'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack Approval
        id: slack-test
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
            channel-id: 'C07BDESKPBQ'
            text: 'Do you approve the deployment to ECS?'
            timeout: 10m
            prompt: yesno
            payload: |
              {
                  "text": "Would you like to play a game?",
                  "attachments": [
                      {
                          "text": "Choose a game to play",
                          "fallback": "You are unable to choose a game",
                          "callback_id": "wopr_game",
                          "color": "#3AA3E3",
                          "attachment_type": "default",
                          "actions": [
                              {
                                  "name": "game",
                                  "text": "Chess",
                                  "type": "button",
                                  "value": "chess"
                              },
                              {
                                  "name": "game",
                                  "text": "Falken's Maze",
                                  "type": "button",
                                  "value": "maze"
                              },
                              {
                                  "name": "game",
                                  "text": "Thermonuclear War",
                                  "style": "danger",
                                  "type": "button",
                                  "value": "war",
                                  "confirm": {
                                      "title": "Are you sure?",
                                      "text": "Wouldn't you prefer a good game of chess?",
                                      "ok_text": "Yes",
                                      "dismiss_text": "No"
                                  }
                              }
                          ]
                      }
                  ]
              }
