name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C07BDESKPBQ'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack Approval
        id: slack
        run: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"channel":"C07BDESKPBQ","text":"Do you approve the deployment to ECS?","attachments":[{"text":"Approve deployment?","fallback":"You are unable to approve","callback_id":"deploy_approval","color":"#3AA3E3","attachment_type":"default","actions":[{"name":"approval","text":"Approve","type":"button","value":"yes"},{"name":"approval","text":"Reject","type":"button","value":"no"}]}]}' \
            https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}"

      - name: Wait for Approval
        id: wait
        run: |
            for i in {1..60}; do
              response=$(curl -s -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" -H "Content-type: application/json" -X POST -d '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","count":1,"inclusive":true}' https://slack.com/api/conversations.history | jq -r '.messages[] | select(.attachments != null) | .attachments[] | select(.callback_id == "deploy_approval") | .actions[] | select(.name == "approval") | .value')
              if [ "$response" == "yes" ] || [ "$response" == "no" ]; then
                echo "response=$response" >> $GITHUB_ENV
                break
              fi
              sleep 10
            done