name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 100 seconds
        run: |
          sleep 100

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Wait for 80 seconds
        run: |
          sleep 80

  job3:
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
      - name: Wait for 60 seconds
        run: |
          sleep 60