name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Approval
        id: slack
        run: |
            response=$(curl -X POST -H 'Content-type: application/json' \
              --data '{"channel":"C07BDESKPBQ","text":"Do you approve the deployment to ECS? (Reply with `yes` or `no`)"}' \
              https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}")
            ts=$(echo $response | jq -r '.ts')
            echo "SLACK_TS=$ts" >> $GITHUB_ENV

      - name: Wait for Approval
        id: wait1
        run: |
          approved=no
          for i in {1..60}; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" -H "Content-type: application/json" \
              "https://slack.com/api/conversations.replies?channel=C07BDESKPBQ&ts=${{ env.SLACK_TS }}")
            if [[ `echo "$response" | jq -r '.messages[1] | select(.text == "yes")'` != "" ]]; then
              approved=yes
              break
            elif [[ `echo "$response" | jq -r '.messages[1] | select(.text == "no")'` != "" ]]; then
              approved=no
              break
            fi
            sleep 10
          done
          echo "approved=$approved" >> $GITHUB_ENV

      - name: test output
        run: |
          echo ${{env.approved}}