name: Check artifact

on:
  push:
    branches:
      - main
jobs:
  save-commit-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit ID
        id: get-commit-id
        run: |
          echo "$(git rev-parse HEAD)" >> hha.txt

      - name: Upload commit_id
        uses: actions/upload-artifact@v4
        with:
          name: idk
          path: hha.txt